# Workflow to Create DNS Record using DNSimple
name: DNSimple Create DNS Record

# Define the events that trigger the workflow
on:
  push:
    branches:
      - my-first-branch  # Trigger on pushes to the "my-first-branch" branch
  workflow_dispatch:  # Manual trigger from GitHub Actions UI

jobs:
  create-dns-record:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu for the job

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Check out the repository's code

    - name: Create DNS Record
      uses: nicklinnell/dnsimple-create-record@v1  # Use the provided DNSimple action
      with:
        token: ${{ secrets.DNSIMPLE_TOKEN }}  # Access token stored as a secret
        account: your_account_number  # Your DNSimple account number
        zone: example.com  # The DNS zone name
        name: subdomain  # The record name (without domain)
        type: A  # Type of DNS record (A, CNAME, etc.)
        content: IPv4_address  # Content of the DNS record (IP address or domain)
        ttl: 3600  # Time to live for the DNS record (optional)
        priority: 10  # Optional priority level of the DNS record
        regions: us-east,eu-west  # Optional set of regions (optional)
        # Comment: This section creates a DNS record using the provided parameters
