name: Cloudflare DNS and Email

on:
  push:
    branches:
      - main  # Adjust the branch name as needed
  workflow_dispatch:

jobs:
  get-all-dns-records-and-send-email:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch All DNS Records
      run: |
        # Replace placeholders with your actual values
        CF_API_TOKEN="HsoabgfSbNQVeHpg30hI14GOo8mZLixzk_7HhJY8"
        ZONE_ID="38b42bfdb42dbe301b6b1a27b86ac939"

        # Construct the API URL to fetch all DNS records
        API_URL="https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records"

        # Send GET request using curl to fetch all DNS records
        DNS_RECORDS=$(curl -s -H "Authorization: Bearer $CF_API_TOKEN" "$API_URL")

        # Save the DNS records to a file
        echo "$DNS_RECORDS" > dns_records.json

    - name: Send Email
      run: python python-scripts.py
